context:
  version: "7.27.1"

package:
  name: babel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@babel/cli/-/cli-${{ version }}.tgz
  sha256: 5c8852751b06b0edbe0b9185af46d7c03ecc59839cf967159e86314ae126877a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - babel --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Babel is a compiler for writing next generation JavaScript.
  homepage: https://github.com/babel/babel-cli
  repository: https://github.com/babel/babel-cli

extra:
  recipe-maintainers:
    - danielnachun
