context:
  version: "7.28.3"

package:
  name: babel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@babel/cli/-/cli-${{ version }}.tgz
  sha256: 7166334788706818cba54d9f4daca3d1f45859e5586dc8a155f187a1ec6d62eb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - babel --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Babel is a compiler for writing next generation JavaScript.
  homepage: https://github.com/babel/babel-cli
  repository: https://github.com/babel/babel-cli

extra:
  recipe-maintainers:
    - danielnachun
